# DOCKERFILE SERVE PRA CRIAR UMA IMAGEM.

# FROM = IMAGEM BASE A SER UTILIZADA
FROM nginx

#COPY = COPIA
# 1 PARAMETRO - CAMINHO DA MINHA MAQUINA
# 2 PARAMETRO - CAMINHO DENTRO CONTAINER
COPY index.html /usr/share/nginx/html

EXPOSE 3333